### ISSUE TITLE
Abstract missing in modal of "Why your domain name matters"

### ISSUE THREAD

**Issue by tonyhhyip** [404busters/hkoscon-2018#17]
![image](https://user-images.githubusercontent.com/9844551/40187924-5426dfea-5a2b-11e8-94ca-6790c672e642.png)

**Comment by yookoala** [comment]
There is no description for the event yet. Pending input from Sammy.

**Comment by tonyhhyip** [comment]
There was an abstraction before

**Comment by yookoala** [comment]
Yes. And it was removed.
