### ISSUE TITLE
Fix issue for GDPR

### ISSUE THREAD

**Issue by tonyhhyip** [404busters/hkoscon-2018#24]
As the website is using GA and Cloudflare which use cookie and 100% sure there is EU citizen for website visitor (at least we have EU speaker), as a result, we are required to fix for according GDPR

**Comment by yookoala** [comment]
@tonyhhyip We don't have a dedicated legal team for this. Also I'm a bit busy recently. Can you please search some website of similar features and paste their links here? We might simply copy and modify their GDPR / Cookie policy notice. Thanks a lot.

**Comment by tonyhhyip** [comment]
Just make some try based the content in https://www.cookiebot.com/en/gdpr-cookies/
![image](https://user-images.githubusercontent.com/9844551/40772545-d4250380-64f2-11e8-8774-d36d2181a00d.png)

**Comment by yookoala** [comment]
Closed by #24.
